server:
  port: ${APP_PORT}
spring:
  application:
    name: NovaTech
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
    web:
      resources:
        static-locations: file:uploads/
    mvc:
      static-path-pattern: /uploads/**


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: backend-service
    server: ${BACKEND_HOST:http://localhost:${APP_PORT}}
    title: Backend service
    version: 1.0.0

api:
  prefix: ${API_PREFIX}